# Generated by Django 5.2.4 on 2025-07-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employeeinfo_applied_for_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinfo',
            name='applied_for_leave',
            field=models.CharField(blank=True, help_text='Example: `06-12->06-15;Emergency Hospital Visit` or null', max_length=50, null=True),
        ),
    ]
