# Generated by Django 5.2.4 on 2025-07-18 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employeeinfo_applied_for_leave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='break_time',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='checkin_time',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='checkout_time',
        ),
        migrations.CreateModel(
            name='EmpStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('checkin_time', models.TimeField()),
                ('checkout_time', models.TimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmpBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('begin_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('empstats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.empstats')),
            ],
        ),
    ]
