# Generated by Django 5.2.4 on 2025-07-18 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_remove_employee_break_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empbreak',
            name='empstats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empbreak', to='employees.empstats'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='online',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='empstats',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empstats', to='employees.employee'),
        ),
    ]
