# Generated by Django 5.2.4 on 2025-07-19 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_alter_empinfo_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='hours_by_day',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='hours_by_month',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='hours_by_week',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='hours_by_years',
        ),
    ]
