# Generated by Django 5.2.4 on 2025-07-20 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_remove_employee_hours_by_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinfo',
            name='leave_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
