# Generated by Django 5.2.4 on 2025-07-21 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_employeeinfo_leave_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='codeEvaluation',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='codeReviews',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='featuresTicked',
        ),
    ]
