# Generated by Django 5.2.4 on 2025-07-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_remove_employee_codeevaluation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='codeEvaluation',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='codeReviews',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='featuresTicked',
            field=models.JSONField(null=True),
        ),
    ]
