# Generated by Django 5.2.4 on 2025-07-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_employee_codeevaluation_employee_codereviews_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empinfo',
            name='hours_by_day',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empinfo',
            name='hours_by_month',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empinfo',
            name='hours_by_weeks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empinfo',
            name='hours_by_years',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
