# Generated by Django 5.2.4 on 2025-07-23 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_empinfo_hours_by_day_empinfo_hours_by_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empinfo',
            name='hours_by_day',
        ),
        migrations.RemoveField(
            model_name='empinfo',
            name='hours_by_month',
        ),
        migrations.RemoveField(
            model_name='empinfo',
            name='hours_by_weeks',
        ),
        migrations.RemoveField(
            model_name='empinfo',
            name='hours_by_years',
        ),
    ]
