# Generated by Django 5.2.4 on 2025-07-23 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_remove_empinfo_hours_by_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_by_day', models.FloatField(blank=True, null=True)),
                ('hours_by_week', models.FloatField(blank=True, null=True)),
                ('hours_by_month', models.FloatField(blank=True, null=True)),
                ('hours_by_years', models.FloatField(blank=True, null=True)),
                ('empinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empinfo', to='employees.empinfo')),
            ],
        ),
    ]
