# Generated by Django 5.2.4 on 2025-07-23 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_hours'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hours',
        ),
    ]
