# Generated by Django 5.2.4 on 2025-07-08 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_leaves_taken', models.IntegerField()),
                ('total_leaves_left', models.IntegerField()),
                ('paid_overtime', models.IntegerField()),
                ('total_absent', models.IntegerField()),
                ('username', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=400)),
                ('job', models.CharField(max_length=300)),
                ('joined', models.DateField()),
                ('codeEvaluation', models.JSONField()),
                ('online', models.BooleanField(default=False)),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('latest_commit', models.CharField(max_length=250)),
                ('hours_by_years', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('age', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254)),
                ('joined', models.DateField()),
                ('latest_commit', models.CharField(max_length=500)),
                ('checkout_time', models.JSONField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
