# Generated by Django 5.2.4 on 2025-07-16 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinfo',
            name='applied_for_leave',
            field=models.CharField(blank=True, help_text='Example: `06-12->06-15` or null', max_length=50, null=True),
        ),
    ]
