# Generated by Django 5.2.4 on 2025-07-18 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_empbreak_empstats_alter_employee_online_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empinfo', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='HourByDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('empinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hour_by_day', to='employees.empinfo')),
            ],
        ),
        migrations.CreateModel(
            name='HourByMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('empinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hour_by_month', to='employees.empinfo')),
            ],
        ),
        migrations.CreateModel(
            name='HourByWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('empinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hour_by_week', to='employees.empinfo')),
            ],
        ),
        migrations.CreateModel(
            name='HourByYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('empinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hour_by_year', to='employees.empinfo')),
            ],
        ),
    ]
