# Generated by Django 5.2.4 on 2025-07-19 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_empinfo_hourbyday_hourbymonth_hourbyweek_hourbyyear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empinfo',
            name='date',
        ),
        migrations.RemoveField(
            model_name='hourbyday',
            name='date',
        ),
        migrations.RemoveField(
            model_name='hourbymonth',
            name='date',
        ),
        migrations.RemoveField(
            model_name='hourbyweek',
            name='date',
        ),
        migrations.RemoveField(
            model_name='hourbyyear',
            name='date',
        ),
        migrations.AddField(
            model_name='hourbyday',
            name='info',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hourbymonth',
            name='info',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hourbyweek',
            name='info',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hourbyyear',
            name='info',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
