# Generated by Django 5.2.4 on 2025-07-19 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_remove_empinfo_date_remove_hourbyday_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empinfo',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empinfo', to='employees.employee'),
        ),
    ]
